### ISSUE TITLE
Some polish suggestions

### ISSUE THREAD

**Issue by billyvg** [boylec/sentry-vsts#3]
- [x] Access Token description adds a space in the URL: https://github.com/boylec/sentry-vsts/blob/master/sentry_vsts/plugin.py#L45
- [ ] URL encode project name here: https://github.com/boylec/sentry-vsts/blob/master/sentry_vsts/plugin.py#L101
- [ ] Can we add a little more detailed descriptions for Project name and User name fields (i.e. specify that these need to be the VSTS names)
- [ ] After issue is created, the VSTS button has an empty dropdown. It should probably have an option to unlink the issue? 
![image](https://user-images.githubusercontent.com/79684/30290631-ea7784fa-96e4-11e7-8270-e9020adf44a9.png)

**Comment by boylec** [comment]
working on these - got the top 3 done just wiring up the last one as well. Thanks for the finds/suggestions 🥇

**Comment by boylec** [comment]
On second thought, maybe the last thing on your list is a symptom of another issue:

This plugin only has the ('create') ability as dictated in lines 17 and 18 of plugin .py

class VstsPlugin(CorePluginMixin, IssuePlugin2):
    allowed_actions = ['create']

The default for IssuePlugin2 is ('create', 'link', 'unlink') which I overrode to only 'create'.

So there are two options, either implement the link/unlink functionality, or hide the "Visual Studio Team Services" button when the only allowed_actions element is 'create'.

What is the intended purpose of the link/unlink functionality for an IssuePlugin2? It seems like it would be rather counter-intuitive for a VSTS plugin to implement that so I'd rather just hide the "Visual Studio Team Services" button for this particular plugin unless you guys have qualms about that?

**Comment by billyvg** [comment]
My mistake... you can just add `unlink` to `allowed_actions` and sentry will handle unlinking. It does not require deleting the Work Item from VSTS, it simply unlinks it from sentry side.

I'm not familiar with VSTS, but will users recognize the acronym? The button currently is pretty wordy:
![image](https://user-images.githubusercontent.com/79684/30341578-635aa70a-97ab-11e7-9240-7c798f7fe846.png)

**Comment by boylec** [comment]
okay cool, I will add it.

I believe the acronym would be fine. I'll change that now.

**Comment by boylec** [comment]
okay those are done #0420b99
