### ISSUE TITLE
Pull into sentry-plugins

### ISSUE THREAD

**Issue by dcramer** [boylec/sentry-vsts#5]
Any objections? Would be happy to add you as a collaborator on the repo, and it ensures that any changes that get pushed will automatically sync to sentry.io.

(We can also maintain the MIT license, or simply transfer it to the shared license in sentry-plugins)

**Comment by boylec** [comment]
no issue at all! :) Thanks.

**Comment by boylec** [comment]
I'll change the license to BSD

**Comment by boylec** [comment]
argh cancel that :P I'll just keep it - do I need to alter anything to pull it in to sentry-plugins?

**Comment by dcramer** [comment]
@boylec nope im converting it over now (just cleaning up a bunch of shared code so its easier to maintain)

**Comment by boylec** [comment]
@dcramer oh haha, okay. I was actually in mid conversion as well. No problem, I'll let you do it since your are more intimately familiar with the goings-on in there. Thanks!
