### ISSUE TITLE
TFS compatible?

### ISSUE THREAD

**Issue by Atrejoe** [boylec/sentry-vsts#7]
Hi,

Is this by any chance TFS compatible?

Regards & thanks for your efforts!

**Comment by boylec** [comment]
Hey there - I signed over all licensing/responsibility for this repo to the sentry team. May want to check with them!

I made it specifically for VSTS originally.

**Comment by Atrejoe** [comment]
Thanks for your prompt response.
Ha, we spoke of this before on the [Sentry forum](https://forum.sentry.io/t/add-integration-with-vsts/103/16?u=robert_cs). I'll monitor progress over htere.
